# Generated by Django 4.2.7 on 2023-11-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_images_remove_size_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
