# Generated by Django 4.2.7 on 2023-12-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=1, upload_to='cart_images/'),
            preserve_default=False,
        ),
    ]
